# Generated by Django 2.2.1 on 2019-05-24 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='city',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
