# Generated by Django 2.2.1 on 2019-05-25 02:41

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('travel_users', '0002_auto_20190523_2205'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='allergies',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='city',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='profile_photo',
            field=models.ImageField(blank=True, upload_to='photos/%Y'),
        ),
    ]
