# Generated by Django 2.2.1 on 2019-06-08 21:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travel_group', '0001_initial'),
        ('travel_users', '0004_auto_20190601_1713'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='travel_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='travel_group', to='travel_group.TravelGroup'),
        ),
    ]
