# Generated by Django 2.2.1 on 2019-06-15 02:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travel_transportation', '0001_initial'),
        ('travel_users', '0005_customuser_travel_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='transportation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='travel_transport', to='travel_transportation.Transportation'),
        ),
    ]
