# Generated by Django 2.2.1 on 2019-07-07 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel_users', '0006_customuser_transportation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='transportation',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='travel_group',
        ),
    ]
