# Generated by Django 3.0.4 on 2021-04-09 02:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travel_group', '0016_travelgroup_group_owner'),
        ('travel_users', '0007_auto_20190707_1552'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='travel_group_invite',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='travel_group_invite', to='travel_group.TravelGroup'),
        ),
    ]
