# Generated by Django 3.0.4 on 2021-04-11 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_group', '0016_travelgroup_group_owner'),
        ('travel_users', '0008_customuser_travel_group_invite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='travel_group_invite',
        ),
        migrations.AddField(
            model_name='customuser',
            name='travel_group_invite',
            field=models.ManyToManyField(blank=True, null=True, related_name='travel_group_invite', to='travel_group.TravelGroup'),
        ),
    ]
