# Generated by Django 3.0.4 on 2021-05-11 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_users', '0010_auto_20210510_2047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_photo',
            field=models.ImageField(blank=True, upload_to='photos/%Y'),
        ),
    ]
