# Generated by Django 2.2.1 on 2019-06-05 01:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import djrichtextfield.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TravelGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trip_name', models.CharField(max_length=200)),
                ('travelers', models.ManyToManyField(related_name='TravelGroup', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TravelMessages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', djrichtextfield.models.RichTextField(blank=True)),
                ('travel_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travel_group.TravelGroup')),
            ],
            options={
                'verbose_name': 'Travel Message',
            },
        ),
        migrations.CreateModel(
            name='SightseeingIdeas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sightseeing_idea', djrichtextfield.models.RichTextField(blank=True)),
                ('travel_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travel_group.TravelGroup')),
            ],
            options={
                'verbose_name': 'Sightseeing Idea',
            },
        ),
        migrations.CreateModel(
            name='RestaurantIdeas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restaurant_idea', djrichtextfield.models.RichTextField(blank=True)),
                ('travel_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travel_group.TravelGroup')),
            ],
            options={
                'verbose_name': 'Restaurant Idea',
            },
        ),
    ]
