# Generated by Django 2.2.1 on 2019-06-13 03:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travel_group', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurantideas',
            name='travel_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restaurant_ideas', to='travel_group.TravelGroup'),
        ),
        migrations.AlterField(
            model_name='sightseeingideas',
            name='travel_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sightseeing_ideas', to='travel_group.TravelGroup'),
        ),
        migrations.AlterField(
            model_name='travelmessages',
            name='travel_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='travel_group.TravelGroup'),
        ),
    ]
