# Generated by Django 2.2.1 on 2019-06-15 02:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travel_transportation', '0001_initial'),
        ('travel_group', '0002_auto_20190612_2159'),
    ]

    operations = [
        migrations.AddField(
            model_name='travelgroup',
            name='transportation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transportation', to='travel_transportation.Transportation'),
        ),
    ]
