# Generated by Django 2.2.1 on 2019-07-07 23:10

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('travel_group', '0003_travelgroup_transportation'),
    ]

    operations = [
        migrations.AddField(
            model_name='travelmessages',
            name='date_created_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='travelmessages',
            name='date_updated_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='travelmessages',
            name='message_creator',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='message_creator', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='travelgroup',
            name='travelers',
            field=models.ManyToManyField(related_name='trav_groups', to=settings.AUTH_USER_MODEL),
        ),
    ]
