# Generated by Django 2.2.1 on 2019-07-29 01:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accommodations', '0003_auto_20190728_1952'),
        ('travel_group', '0004_auto_20190707_1710'),
    ]

    operations = [
        migrations.AddField(
            model_name='travelgroup',
            name='accommodations',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accommodation', to='accommodations.Accommodations'),
        ),
    ]
