# Generated by Django 2.2.1 on 2019-09-05 03:01

from django.db import migrations, models
import django.db.models.deletion
import djrichtextfield.models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_group', '0005_travelgroup_accommodations'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChecklistItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checklist_item', djrichtextfield.models.RichTextField(blank=True)),
                ('travel_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist_items', to='travel_group.TravelGroup')),
            ],
            options={
                'verbose_name': 'Checklist Items',
            },
        ),
    ]
