# Generated by Django 2.2.1 on 2019-09-06 02:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('travel_group', '0006_checklistitems'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklistitems',
            name='checklist_creator',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='checklist_creator', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
