# Generated by Django 2.2.1 on 2019-09-09 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_group', '0007_checklistitems_checklist_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklistitems',
            name='item_status',
            field=models.BooleanField(default=False),
        ),
    ]
