# Generated by Django 3.0.4 on 2020-06-06 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_group', '0010_restaurantideas_restaurant_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='travelgroup',
            name='primary_destination',
            field=models.CharField(default='', max_length=200),
        ),
    ]
