# Generated by Django 3.0.4 on 2020-06-11 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_group', '0011_travelgroup_primary_destination'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnsplashPhotos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.CharField(blank=True, max_length=400)),
            ],
        ),
    ]
