# Generated by Django 3.0.4 on 2020-08-30 23:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travel_group', '0012_unsplashphotos'),
    ]

    operations = [
        migrations.AddField(
            model_name='travelgroup',
            name='photo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='display_photo', to='travel_group.UnsplashPhotos'),
        ),
    ]
