# Generated by Django 3.0.4 on 2020-11-24 04:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel_group', '0014_auto_20200830_1804'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='travelgroup',
            name='photo',
        ),
    ]
