# Generated by Django 3.0.4 on 2021-04-05 02:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('travel_group', '0015_remove_travelgroup_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='travelgroup',
            name='group_owner',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='travel_group_owner', to=settings.AUTH_USER_MODEL),
        ),
    ]
