# Generated by Django 3.0.4 on 2021-05-24 02:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('travel_group', '0016_travelgroup_group_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travelgroup',
            name='travelers',
            field=models.ManyToManyField(blank=True, null=True, related_name='trav_groups', to=settings.AUTH_USER_MODEL),
        ),
    ]
