# Generated by Django 2.2.1 on 2019-07-25 02:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travel_group', '0004_auto_20190707_1710'),
        ('accommodations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accommodations',
            name='trip',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='user_trip', to='travel_group.TravelGroup'),
            preserve_default=False,
        ),
    ]
