# Generated by Django 2.2.1 on 2019-10-13 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accommodations', '0004_auto_20190904_2048'),
    ]

    operations = [
        migrations.AddField(
            model_name='accommodations',
            name='website',
            field=models.URLField(blank=True),
        ),
    ]
