# Generated by Django 2.2.1 on 2019-08-10 22:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travel_group', '0005_travelgroup_accommodations'),
        ('travel_transportation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transportation',
            name='travel_group',
            field=models.ForeignKey(default='', limit_choices_to={'travelers': True}, on_delete=django.db.models.deletion.CASCADE, related_name='group_transport', to='travel_group.TravelGroup'),
            preserve_default=False,
        ),
    ]
