# Generated by Django 2.2.1 on 2019-08-11 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_transportation', '0002_transportation_travel_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='transportation',
            name='carrier',
            field=models.CharField(blank=True, help_text='Enter the carrier company name, such as United or Delta', max_length=255),
        ),
        migrations.AlterField(
            model_name='transportation',
            name='name',
            field=models.CharField(blank=True, help_text='Provide a name for this transportation (e.g., Madrid Return Flight)', max_length=200),
        ),
    ]
