# Generated by Django 3.0.4 on 2020-05-03 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_transportation', '0003_auto_20190811_1435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transportation',
            name='flight_no',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
