# Generated by Django 3.0.4 on 2020-12-28 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accommodation_photo', models.CharField(blank=True, default='', max_length=600)),
                ('accommodation_photo_attribution', models.CharField(blank=True, default='', max_length=600)),
                ('profile_photo', models.CharField(blank=True, default='', max_length=600)),
                ('profile_photo_attribution', models.CharField(blank=True, default='', max_length=600)),
                ('transportation_photo', models.CharField(blank=True, default='', max_length=600)),
                ('transportation_photo_attribution', models.CharField(blank=True, default='', max_length=600)),
                ('travelgroup_photo', models.CharField(blank=True, default='', max_length=600)),
                ('travelgroup_photo_attribution', models.CharField(blank=True, default='', max_length=600)),
            ],
        ),
    ]
