# Generated by Django 3.0.4 on 2021-01-03 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0002_auto_20201231_2200'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='restaurant_photo',
            field=models.CharField(blank=True, default='', max_length=600),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='restaurant_photo_attribution',
            field=models.CharField(blank=True, default='', max_length=600),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='sightseeing_photo',
            field=models.CharField(blank=True, default='', max_length=600),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='sightseeing_photo_attribution',
            field=models.CharField(blank=True, default='', max_length=600),
        ),
    ]
